# Generated by Django 4.2.4 on 2023-08-11 12:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('obects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superadmin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
