# Generated by Django 4.2.4 on 2023-09-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('Image', models.ImageField(upload_to='photos/books')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('self-help', 'self-help'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Child', 'Child'), ('History', 'History'), ('Health', 'Health')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
