# Generated by Django 4.2.4 on 2023-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Image',
            field=models.ImageField(upload_to='photos/books'),
        ),
    ]
