# Generated by Django 4.2.4 on 2023-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('self-help', 'self-help'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Child', 'Child'), ('History', 'History'), ('Health', 'Health'), ('Biography', 'Biography'), ('Fiction and Literature', 'Fiction and Literature'), ('Sprituality and philosophy', 'Sprituality and Philosophy')], max_length=100),
        ),
    ]
